version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "guacamole_db"
      POSTGRES_USER: "guacamole_usr"
      POSTGRES_PASSWORD: "guacamole_pass"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./postgres:/var/lib/postgresql/data
  
  guacd:
    image: guacamole/guacd
  
  guacamole:
    image: guacamole/guacamole
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: "guacamole_db"
      POSTGRES_USER: "guacamole_usr"
      POSTGRES_PASSWORD: "guacamole_pass"
      GUACAMOLE_HOME: /etc/guacamole
    volumes:
      - ./user-mapping.xml:/etc/guacamole/user-mapping.xml

  chrome:
    image: selenium/standalone-chrome-debug

  firefox:
    image: selenium/standalone-firefox-debug
